package com.my.dao;

import com.my.entity.Student;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Thu Mar 14 16:43:02 CST 2019
     */
    @Delete({
        "delete from t_student",
        "where pk_id = #{pkId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Thu Mar 14 16:43:02 CST 2019
     */
    @Insert({
        "insert into t_student (pk_id, f_name, ",
        "f_age)",
        "values (#{pkId,jdbcType=INTEGER}, #{fName,jdbcType=VARCHAR}, ",
        "#{fAge,jdbcType=INTEGER})"
    })
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Thu Mar 14 16:43:02 CST 2019
     */
    @InsertProvider(type=StudentSqlProvider.class, method="insertSelective")
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Thu Mar 14 16:43:02 CST 2019
     */
    @Select({
        "select",
        "pk_id, f_name, f_age",
        "from t_student",
        "where pk_id = #{pkId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="pk_id", property="pkId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="f_name", property="fName", jdbcType=JdbcType.VARCHAR),
        @Result(column="f_age", property="fAge", jdbcType=JdbcType.INTEGER)
    })
    Student selectByPrimaryKey(Integer pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Thu Mar 14 16:43:02 CST 2019
     */
    @UpdateProvider(type=StudentSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Thu Mar 14 16:43:02 CST 2019
     */
    @Update({
        "update t_student",
        "set f_name = #{fName,jdbcType=VARCHAR},",
          "f_age = #{fAge,jdbcType=INTEGER}",
        "where pk_id = #{pkId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Student record);
}