package com.my.dao;

import com.my.entity.Student;
import org.apache.ibatis.jdbc.SQL;

public class StudentSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Thu Mar 14 16:43:02 CST 2019
     */
    public String insertSelective(Student record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_student");
        
        if (record.getPkId() != null) {
            sql.VALUES("pk_id", "#{pkId,jdbcType=INTEGER}");
        }
        
        if (record.getfName() != null) {
            sql.VALUES("f_name", "#{fName,jdbcType=VARCHAR}");
        }
        
        if (record.getfAge() != null) {
            sql.VALUES("f_age", "#{fAge,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Thu Mar 14 16:43:02 CST 2019
     */
    public String updateByPrimaryKeySelective(Student record) {
        SQL sql = new SQL();
        sql.UPDATE("t_student");
        
        if (record.getfName() != null) {
            sql.SET("f_name = #{fName,jdbcType=VARCHAR}");
        }
        
        if (record.getfAge() != null) {
            sql.SET("f_age = #{fAge,jdbcType=INTEGER}");
        }
        
        sql.WHERE("pk_id = #{pkId,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}