package com.my.entity;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.pk_id
     *
     * @mbg.generated Thu Mar 14 16:43:02 CST 2019
     */
    private Integer pkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.f_name
     *
     * @mbg.generated Thu Mar 14 16:43:02 CST 2019
     */
    private String fName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.f_age
     *
     * @mbg.generated Thu Mar 14 16:43:02 CST 2019
     */
    private Integer fAge;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.pk_id
     *
     * @return the value of t_student.pk_id
     *
     * @mbg.generated Thu Mar 14 16:43:02 CST 2019
     */
    public Integer getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.pk_id
     *
     * @param pkId the value for t_student.pk_id
     *
     * @mbg.generated Thu Mar 14 16:43:02 CST 2019
     */
    public void setPkId(Integer pkId) {
        this.pkId = pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.f_name
     *
     * @return the value of t_student.f_name
     *
     * @mbg.generated Thu Mar 14 16:43:02 CST 2019
     */
    public String getfName() {
        return fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.f_name
     *
     * @param fName the value for t_student.f_name
     *
     * @mbg.generated Thu Mar 14 16:43:02 CST 2019
     */
    public void setfName(String fName) {
        this.fName = fName == null ? null : fName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.f_age
     *
     * @return the value of t_student.f_age
     *
     * @mbg.generated Thu Mar 14 16:43:02 CST 2019
     */
    public Integer getfAge() {
        return fAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.f_age
     *
     * @param fAge the value for t_student.f_age
     *
     * @mbg.generated Thu Mar 14 16:43:02 CST 2019
     */
    public void setfAge(Integer fAge) {
        this.fAge = fAge;
    }
}